import type { FamilySiteLabels } from "../types/config";

export const defaultLabels: FamilySiteLabels = {
  navHome: "Home",
  navTree: "Family Tree",
  navMembers: "Members",
  navGallery: "Gallery",
  navTimeline: "Timeline",
  navAdmin: "Manage",
  allMembers: "All Members",
  allGenerations: "All Generations",
  allBranches: "All Branches",
  deceased: "Deceased",
  coreFamily: "Core Family",
  membersFound: "members found",
  branchSummaryFallback: "All family records are documented in this archive.",
  memberBiographyFallback: "is recorded in the family archive. The biography can be completed later by the family.",
  relationshipPlaceholder: "Example: Grandchild of family founder",
  importMembersHelp: "Paste structured JSON of family members to replace local data in this browser.",
  emptyMembersTitle: "No family members yet.",
  emptyMembersDescription: "Family data can be added from the admin panel once the database is ready.",
  emptyGalleryTitle: "No family photos yet.",
  emptyGalleryDescription: "Photo archives can be added from the admin panel.",
  emptyTimelineTitle: "No records for this selection.",
  emptyTimelineDescription: "Try selecting 'All' to see the entire family story.",
  statusOptions: ["Main Line", "Extended Family", "In-law", "Child", "Grandchild", "Great-grandchild", "Relative"],
};
